# Generated by Django 4.1.2 on 2022-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('DOB', models.DateField()),
                ('Mobile', models.IntegerField(default=True)),
                ('AlterMobile', models.IntegerField(default=True)),
                ('Email', models.EmailField(default=True, max_length=254)),
                ('Maritual_status', models.BooleanField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')])),
                ('Blood', models.CharField(max_length=10)),
            ],
        ),
    ]
