# Generated by Django 4.1.2 on 2022-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='AlterMobile',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='Mobile',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
