# Generated by Django 4.1.2 on 2022-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_alter_addemployee_altermobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='Maritual_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10),
        ),
    ]
