# Generated by Django 4.1.2 on 2022-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_alter_addemployee_maritual_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='AlterMobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
